plugins:
  bundler-audit:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-21-0