version = 1

test_patterns = [
  "spec/**",
  "*_spec.rb"
]

exclude_patterns = [
  "vendor/**"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true
