require:
  - rubocop-rake
  - rubocop-rspec
inherit_gem:
  rubocop-rake: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.0.2
  EnabledByDefault: true
  NewCops: enable
  Exclude:
    - 'bin/tapioca'
    - "vendor/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/AccessModifierDeclarations:
  Enabled: false
