---
language: ruby
os: linux
dist: focal
cache: bundler
rvm:
  - 3.0.2
env:
  - TEST_SCRIPT="bundle exec rake spec"
  - TEST_SCRIPT="bundle exec rake rubocop"
before_install: gem install bundler -v 2.2.22
script: "${TEST_SCRIPT}"
# jobs:
#   include:
#     - stage: Tests
#       script: bundle exec rake spec
#     - stage: Rubocop
#       script: bundle exec rake rubocop
#     - stage: Bundler Audit
#       script: bundle exec bundler-audit
#     - stage: Markdown Linter
#       script: bundle exec mdl -c .mdlrc README.md
#     - stage: Reek
#       script: bundle exec reek
#     - stage: Churn
#       script: bundle exec churn
#     - stage: FIXME Check
#       script: egrep -r "TODO|FIXME|HACK|BUG|XXX" *
