---
language: ruby
dist: focal
cache: bundler
rvm:
  - 3.0.2
before_install: gem install bundler -v 2.2.22
jobs:
  include:
    - stage: Markdown Linter
      script: bundle exec mdl -c .mdlrc README.md
