---
language: ruby
os: linux
dist: focal
cache: bundler
rvm:
  - 3.0.2
env:
  - TEST_SCRIPT="bundle exec rake spec"
  - TEST_SCRIPT="bundle exec rake rubocop"
  - TEST_SCRIPT="bundle exec bundler-audit"
  - TEST_SCRIPT="bundle exec mdl -c .mdlrc README.md"
  - TEST_SCRIPT="bundle exec reek"
  - TEST_SCRIPT="bundle exec churn"
  - TEST_SCRIPT="egrep -r 'TODO|FIXME|HACK|BUG|XXX' *"
before_install: gem install bundler -v 2.2.22
script: "${TEST_SCRIPT}"
